apiVersion: 1.0.0
kind: ServiceAccount
data:
  name: account-2
  annotations:
    "vgs.io/vault-id": "tntxpawymkh"
    "vgs.io/sub-account": "account-2"
  scopes:
    - name: financial-instruments:write
      optional: true
    - name: transfers:write
      optional: true
    - name: transfers:admin
      optional: true
    - name: orders:write
      optional: true

  accessTokenLifespan: 28800
