apiVersion: 1.0.0
kind: ServiceAccount
data:
  name: ~NAME~
  annotations:
    "vgs.io/vault-id": "~VAULT_ID~"
    "vgs.io/sub-account": "~NAME~"
  scopes:
    - name: financial-instruments:write
      optional: true
    - name: transfers:write
      optional: true
    - name: transfers:admin
      optional: true
    - name: orders:write
      optional: true

  accessTokenLifespan: 28800
